services:
  db:
    image: postgres:13-alpine
    volumes:
      - db:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=$PGUSER
      - POSTGRES_PASSWORD=$PGPASSWORD
      - POSTGRES_DB=$PGDB
  web:
    build: .
    command: python main.py
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always
volumes:
  db:
    driver: local